// import run from '/leetcode/1_two_sum.js'
// import run from '/leetcode/121_buy_sell_stock'
// import run from '/leetcode/217_contains_duplicate'
// import run from '/leetcode/238_product_of_array_except_self'
// import run from '/leetcode/53_maximum_subarray'
// import run from '/leetcode/152_maximum_product_subarray'
// import run from '/leetcode/33_search_in_rotated_sorted_array'
// import run from '/leetcode/15_3Sum'
// import run from '/leetcode/11_container_with_most_water'
// import run from '/leetcode/239_sliding_window_maximum'
// import run from '/leetcode/242_validAnagram'
// import run from '/leetcode/3_longest_substring_without_repeating_characters'
// import run from '/leetcode/424_longest_repeating_character_replacement'
// import run from '/leetcode/438_find_all_anagrams_in_a_string'
// import run from '/leetcode/76_minimum_window_substring'
// import run from '/leetcode/49_group_anagrams'
// import run from '/leetcode/5_longest_palindromic_substring'
// import run from '/leetcode/383_ransom_note'
// import run from '/leetcode/380_insert_delete_getRandom_O'
// import run from '/leetcode/41_first_missing_positive'
import run from '/leetcode/146_LRU_cache'

run()
